version: "2"

services:
  appserver:
    image: sebglazebrook/personal-website
    ports:
      - 9292
    restart: always
    networks:
      sebglazebrook:
        aliases:
          - "main-website"

networks:
  sebglazebrook:
    external:
      name: "sebglazebrook"
