#!/usr/bin/env ruby
require_relative "../lib/application"
require "commands/add_new_blog_post"

LOGGER.info "Reading from stdin"
blog_post_data = STDIN.read
Commands::AddNewBlogPost.new(blog_post_data).call
